version: "3.8"
services:
  app:
    build:
      context: ./
      target: runner
      args:
        NODE_ENV: $NODE_ENV
        MYSQL_HOST: $MYSQL_HOST
        MYSQL_PORT: $MYSQL_PORT
        MYSQL_DB: $MYSQL_DB
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: yarn start
  # mysql-db:
  #   container_name: mysql-db
  #   build: ./Database
  #   env_file: .env
  #   volumes:
  #    - ./Database/:/scripts/
  #   ports:
  #     - "3007:3007"
  #   expose:
  #     - "1433"
  #   command:
  #     - mysql