name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag patient-manager:$(date +%s)

  exec:

    runs-on: ubuntu-latest
    environment: production
    needs: build

    steps:
    - name: Run the Docker image
      run: docker run patient-manager:latest

    
