name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build

  exec:

    runs-on: ubuntu-latest
    environment: production
    needs: build

    steps:
    - name: Run the Docker image
      run: docker-compose up

    
